version: "3.3"
services:
  bot:
    build: .
    volumes:
      - ./cache:/var/cache
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      TELEGRAM_USER_ID: ${TELEGRAM_USER_ID}
    network_mode: "host"
    restart: unless-stopped
