version: "3.3"
services:
  bot:
    build: .
    volumes:
      - ./cache:/var/cache/birthdays-lord-bot
    environment:
      - TELEGRAM_API_TOKEN
      - TELEGRAM_USER_IDS
      - GOOGLE_SHEETS_CREDENTIALS_FILE
      - DEVMODE
    network_mode: "host"
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "5"
